[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/user/data"
  to = "/.netlify/functions/user-data"
  status = 200

[[redirects]]
  from = "/api/user/data/*"
  to = "/.netlify/functions/user-data"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/uploads/*"
  to = "/.netlify/functions/uploads/:splat"
  status = 200

[[redirects]]
  from = "/shared/*"
  to = "/.netlify/functions/shared/:splat"
  status = 200
